### ISSUE TITLE
Quick advice about the readme

### ISSUE THREAD

**Issue by Abacate123** [Magisk-Modules-Alt-Repo/Google-Sans-Plus#1]
Hi! I loved your Sans module, it's simple, and it works amazingly. Thanks.

There are no issues just a feedback. My advice here is a simple detail, your readme states that you need Android 9+ as a requirement to install this module, well, I'm on 8.0 and it's working just fine as it should, either the fonts and the emojis. So that's basically it.

**Comment by sourajitk** [comment]
https://github.com/Magisk-Modules-Alt-Repo/Google-Sans/commit/ae396fae0c54da51603589eca74f6962f7e4a2d4

Done!
